Moved alm2map to init of PrecomputedAlms ; added CAR support
zonca/so_pysm_models pull request #1
Opened 2018-12-20 21:29 UTC by msyriac

Not ready for review yet. Still testing.

2018-12-21 00:08 UTC, msyriac commented
I've made a first pass at integrating mapsims.cmb and so_pysm_models.alms. Could you have a look?

2019-01-02 22:04 UTC, zonca requested changes
very good, thanks! I left a couple of minor comments

2019-01-02 22:04 UTC, zonca commented on so_pysm_models/alms.py
> +            nu = [148.0]
I think a default value should be in the function signature, what about having `nu=[148.0]` as input argument?

2019-01-02 22:04 UTC, zonca commented on so_pysm_models/alms.py
> +            self.omap = enmap.empty((ncomp,) + self.shape[-2:], self.wcs)
I think a little more verbose names are easier to understand, can you replace `omap` with `output_map`?
also can you replace `ncomp` with `n_comp`?

2019-01-02 22:04 UTC, zonca commented on so_pysm_models/alms.py
> +    def signal(self, nu=None, modulation=True, output_units="uK_RJ", **kwargs):
as modulation is not implemented, can you leave it  completely out for now?
once that is implemented, maybe we will discover that we have a better way to specify it instead of a boolean keyword in this function.

2019-01-03 03:22 UTC, msyriac commented on so_pysm_models/alms.py
> +    def signal(self, nu=None, modulation=True, output_units="uK_RJ", **kwargs):
Sure.

2019-01-03 03:23 UTC, msyriac commented on so_pysm_models/alms.py
> +            self.omap = enmap.empty((ncomp,) + self.shape[-2:], self.wcs)
Sure.

2019-01-03 03:23 UTC, msyriac commented on so_pysm_models/alms.py
> +            nu = [148.0]
Done.

2019-01-03 03:24 UTC, msyriac commented
Responded to review; ready for merging.

2019-01-03 04:08 UTC, zonca approved these changes

2019-01-03 04:08 UTC, merged